### ISSUE TITLE
可以使用摄像头吗

### ISSUE THREAD

**Issue by stephen-TT** [NagatoYuki0943/yolov8-infer#2]
请问在运行 trt_infer.py 程序的时候，怎么修改才能使用摄像头

**Comment by NagatoYuki0943** [comment]
可以参考这个项目 https://github.com/bubbliiiing/yolov8-pytorch/blob/master/predict.py#L95-L139 ，将 113 行的 frame 丢给  inference.single(frame, only_get_result=False, ignore_overlap_box=False) 就可以了
```python
frame = cv2.cvtColor(frame,cv2.COLOR_BGR2RGB)
result, image_bgr_detect = inference.single(frame, only_get_result=False, ignore_overlap_box=False)
```

**Comment by stephen-TT** [comment]
好的，谢谢大佬
